[package]
name = "bytecloak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#OAuth2
oauth2 = "4.4.0" #latest 4.4.2
reqwest = { version = "0.11", featuers = ["json"] } # HTTP client
tokio = { version = "1", features = ["full"] } # Async Runtime
#Other Dependencies
anyhow = "1.0.75"
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
rand = "0.8"
walkdir = "2.4.0"
glob = "0.3.1"
dunce = "1.0.4"
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
toml = { version = "0.8.4", features = ["display"] }
envy = "0.4.2"
dotenv = "0.15.0"
clap = { version = "4.4.8", features = ["derive", "cargo"] }

