[package]
name = "bytecloak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
cocoon = { version = "0.4.0", features = ["std"] }
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
rand = "0.8"
walkdir = "2.4.0"
glob = "0.3.1"
